version: "3.8"

services:
    backend_template:
        build:
            dockerfile: ./Dockerfile
        command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        # command: bash -c "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        restart: on-failure
        depends_on:
            - db_template
    db_template:
        image: postgres:15.3
        ports:
            - "5434:5434"
        env_file: ./.env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - db_template_data:/var/lib/postgresql/data

volumes:
    db_template_data:
